#spring.jpa.hibernate.ddl-auto=update
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml


